Bookers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#root'
  get '/home/about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]

  resources :books, except: :new do
  	resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy] 
  end
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 50 }
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

Bookers/app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

Bookers/app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

Bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, :except=>[:root, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_up_path_for(resource)
     user_path(resource)
  	end
  	def after_sign_in_path_for(resource)
	 user_path(resource)
	end

	protected

	def configure_permitted_parameters
		added_attrs = [ :name, :email, :password, :password_confirmation]
		devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end
end

Bookers/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = book.id
		comment.save
		redirect_back(fallback_location: root_path)
	end
	def destroy
		comment = BookComment.find(params[:book_id])
		comment.destroy
		redirect_back(fallback_location: root_path)
	end

	private 
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@new_book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
  	@user = current_user
    @new_book = Book.new
  	@books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    #user.id == @book.user_id
  	@user = User.find_by(id: @book.user_id)
    @new_book = Book.new
    @comment = BookComment.new
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "You have update book successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    user = current_user
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def correct_user
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user_id == current_user.id
  end
end

Bookers/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end
	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id:book.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

Bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def root
  end

  def about
  end
  
end

Bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def index
  	@user = current_user
    @new_book = Book.new
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @new_book = Book.new
  	@books = Book.where(user_id: params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have update user successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Bookers/app/helpers/book_helper.rb
module BookHelper
end

Bookers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers/app/helpers/users_helper.rb
module UsersHelper
end

Bookers/app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>

			<% if @book.errors.any? %>
			  <div id="error_explanation">
			    <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
			    <ul>
			    <% @book.errors.full_messages.each do |msg| %>
			      <li><%= msg %></li>
			    <% end %>
			    </ul>
			  </div>
			<% end %>

			<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
				<div class="field row">
					<label for="book_title">Title</label>
					<%= f.text_field :title, class: "book_title col-xs-12" %>
				</div>
				<div class="field row">
					<label for="book_opinion">Opinion</label>
					<%= f.text_area :body, class: "book_opinion col-xs-12" %>
				</div>
				<div class="action row">
				<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
				</div>
			<% end %>
			<%= link_to "Show", book_path(@book.id) %>
			|
			<%= link_to "Back", books_path %>
		</div>
	</div>
</div>

Bookers/app/views/books/index.html.erb
<%= render partial: 'users/sidebar', locals: {user:@user, new_book:@new_book} %>
<div class="col-xs-9">
	<h2>Books</h2>
	<table  class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>&nbsp;</th>
				<th>Title</th>
				<th>Opinion</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<% @books.each do |book| %>
			<tr>
				<td>
					<%= link_to user_path(book.user_id) do %>
						<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
					<% end %>	
					</td>
				<td><%= link_to book.title, book_path(book.id) %></td>
				<td><%= book.body %></td>
				<td>
				<% if book.favorited_by?(current_user) %>
					<%= link_to book_favorites_path(book), method: :delete do %>
					<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
					<%= book.favorites.count %>
					<% end %>
				<% else %>
					<%= link_to book_favorites_path(book), method: :post do %>
					<i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
					<%= book.favorites.count %>
					<% end %>
				<% end %>
				</td>
				<td>
					コメント数：<%= book.book_comments.count %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

Bookers/app/views/books/show.html.erb
<%= render partial: 'users/sidebar', locals: {user:@user, new_book:@new_book} %>
<div class="col-xs-9">
	<h2>Book detail</h2>

	<table class="table">
		<td>
			<%= link_to user_path(@user.id) do %>
				<%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
			<% end %><br>		
			<%= link_to @user.name, user_path(@user.id) %>
		</td>
		<td><%= @book.title %></td>
		<td><%= @book.body %></td>

		<td>
			<% if @book.favorited_by?(current_user) %>
				<%= link_to book_favorites_path(@book), method: :delete do %>
				<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
				<%= @book.favorites.count %>
				<% end %>
			<% else %>
				<%= link_to book_favorites_path(@book), method: :post do %>
				<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
				<%= @book.favorites.count %>
				<% end %>
			<% end %>
		</td>

		<td>コメント数：<%= @book.book_comments.count %></td>

		<% if @book.user == current_user %>
		<td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
		<td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" , class: "btn btn-danger btn-sm" %></td>
		<% end %>
	</table>
	<% @book.book_comments.each do |book_comment| %>
		<table>
			<tr>
				<td>
					<%= link_to user_path(book_comment.user_id) do %>
					<%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %><br>
					<%= book_comment.user.name %>
					<% end %>
				</td>
				<td><%= book_comment.comment %>	</td>
				<td>
					<% if book_comment.user == current_user %>
						<%= link_to "Destroy", book_book_comments_path(book_comment), method: :delete, class: "btn btn-danger btn-sm" %>
					<% end %>
				</td>
			</tr>
		</table>
	<% end %>
	<div class="row">
	<%= form_for [@book, @comment] do |f| %>
		<div class="field col-xs-10">
			<%= f.text_area :comment, class: "col-xs-12 comment-field" %>
		</div>
		<div class="action col-xs-2">
			<%= f.submit "送信", class: "comment-submit" %>
		</div>
	</div>
	<% end %>
</div>

Bookers/app/views/homes/about.html.erb
<div class="container">
	<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers!<strong></h1>
</div>

Bookers/app/views/homes/root.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers<strong> !!</h1>
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers<strong>,</strong>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about various books!</p>
			<div class="row">
				<%= link_to "Log in", "/users/sign_in", class: "btn btn-info col-xs-10 col-xs-offset-1" %>
			</div>
			<div class="row">
				<%= link_to "Sign Up", "/users/sign_up", class: "btn btn-success col-xs-10 col-xs-offset-1" %>
			</div>
		</div>
	</div>
</div>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-header navbar-left">
          <h4 class="header-logo">Bookers</h4>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id) do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path do %>
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path do %>
                  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                  Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                logout
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path do %>
                  <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                  About
                <% end %>
              </li>
              <li>
                <%= link_to "/users/sign_up" do %>
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                  sign up
                <% end %>
              </li>
              <li>
                <%= link_to "/users/sign_in" do %>
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                  login
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="main container">
      <div class="row">
        <% if flash[:notice] %>
          <div>
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

Bookers/app/views/users/_sidebar.html.erb
<div class="col-xs-3">
	<h2>User info</h2>
	<%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
	<table class="table">
		<tr></tr>
		<tr>
			<th>name</th>
			<td><%= user.name %></td>
		</tr>
		<tr>
			<th>introduction</th>
			<td><%= user.introduction %></td>
		</tr>
	</table>
	<div class="row">
		<%= link_to edit_user_path(user.id), {:class => "btn btn-default col-xs-12"} do %>
			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
		<% end %>
	</div>

	<h2>New book</h2>

	<% if new_book.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= new_book.errors.count %> errors prohibited this obj from being saved:</h2>
	    <ul>
	    <% new_book.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>

	<%= form_for(new_book, url:'/books') do |f| %>
		<div class="field row">
			<label for="book_title">Title</label>
			<%= f.text_field :title, class: "col-xs-12 book_title" %>
		</div>
		<div class="field row">
			<label for="book_opinion">Opinion</label>
			<%= f.text_area :body, class: "col-xs-12 book_opinion" %>
		</div>
		<div class="actions row">
			<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
		</div>
	<% end %>
</div>

Bookers/app/views/users/edit.html.erb
<h2>User info</h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@user) do |f| %>
    <div class="field">
        <label>Name</label>
        <%= f.text_field :name, autofocus: true, placeholder:"", class: "name" %>
    </div>
    <div class="field">
        <label>Image</label>
        <%= f.attachment_field :profile_image, class: "image" %>
    </div>
    <div class="field">
        <label>Introduction</label>
        <%= f.text_area :introduction, autofocus: true, placeholder:"", class: "introduction" %>
    </div>
    <div class="actions">
        <%= f.submit "Update User" %>
    </div>
<% end %>

Bookers/app/views/users/index.html.erb
<%= render partial: 'users/sidebar', locals: {user:@user, new_book:@new_book} %>
<div class="col-xs-9">
	<h2>Users</h2>
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
				<td><%= user.name %></td>
				<td><%= link_to "Show", user_path(user.id) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

Bookers/app/views/users/show.html.erb
<%= render partial: 'users/sidebar', locals: {user:@user, new_book:@new_book} %>

<div class="col-xs-9">
	<h2>Books</h2>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>&nbsp;</th>
				<th>Title</th>
				<th>Opinion</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<% @books.each do |book| %>
			<tr>
				<td><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
				<td><%= link_to book.title, book_path(book.id) %></td>
				<td><%= book.body %></td>
				<td>コメント数：<%= book.book_comments.count %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>